version: '3.8'

services:
  web:
    image: grzegorzopara/k8s-sample-app:1.0
    command: python app.py
    volumes: # mounts local folder for quick development
       - ./app:/app
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16.1
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/gelo/k8s/volume/postgresql
      o: bind