apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: k8s-sample-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: grzegorzopara/k8s-sample-app:1.3
        ports:
        - name: app
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-cm
        env:
        - name: POSTGRES_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_CONN_STRING
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"