apiVersion: v1
kind: Service
metadata:
  name: db  # Replace with your desired service name
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
