apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: app-monitoring
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
  - port: app
    scheme: http
    interval: 30s
    path: /metrics