apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: db-monitoring
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
  - port: prometheus
    scheme: http
    interval: 30s
    path: /metrics